version: "3"

services:
  gitea-db:
    image: postgres:13
    container_name: gitea-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - gitea-db-data:/var/lib/postgresql/data
    networks:
      - gitea-network

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - GITEA__server__ROOT_URL=${ROOT_URL}
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
    depends_on:
      - gitea-db
    networks:
      - gitea-network

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner-1
    environment:
      - GITEA_INSTANCE_URL=${ROOT_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN_1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea
    networks:
      - gitea-network

  gitea-runner-2:
    image: gitea/act_runner:latest
    container_name: gitea-runner-2
    environment:
      - GITEA_INSTANCE_URL=${ROOT_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN_2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea
    networks:
      - gitea-network

volumes:
  gitea-db-data:
    driver: local
  gitea-data:
    driver: local

networks:
  gitea-network:
    driver: bridge
